MTE-5304: Add Syndicated Content Features to Solve.
rackerlabs/solve pull request #32
Opened 2020-01-17 20:10 UTC by pobtastic

https://jira.rax.io/browse/MTE-5304

2020-01-17 20:16 UTC, WidgetsBurritos commented
Preview URL: http://mte-5304-syndicated-content.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5304-syndicated-content.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

2020-01-17 20:16 UTC, runrog approved these changes
👍

2020-01-20 17:16 UTC, WidgetsBurritos commented
Preview URL: http://mte-5304-syndicated-content.solve.dev.website.rackspace.com/solve

Login Url: http://mte-5304-syndicated-content.solve.dev.website.rackspace.com/user

_Note: If your branch name contains underscores or periods, replace them with hyphens prior to attempting to access the links above._

2020-01-21 19:09 UTC, WidgetsBurritos requested changes

2020-01-21 19:09 UTC, WidgetsBurritos commented on src/pages/solve-overview/template.html
> +              <span class="rsTl-feature-author" v-else>{{ featured.first.field_author }}</span> – {{ getDateString(featured.first.field_published_date) }}
As mentioned on the www PR. We need to add the company name here too per the ticket. 

> If the syndicated content checkbox is unchecked, display the company name next to the author's name
> - Use the Company field on Author, Leadership, and Event Speaker content types
> - For example Matt Stoyka / Rackspace

I believe we'll need to add company name to the api export to accomplish this.

2020-01-22 21:22 UTC, WidgetsBurritos commented on src/pages/solve-overview/template.html
> +              <span class="rsTl-feature-author" v-else>{{ featured.first.field_author }}</span> – {{ getDateString(featured.first.field_published_date) }}
This has been resolved on the Drupal side.  We're good here.

2020-01-22 21:22 UTC, WidgetsBurritos approved these changes
👍 LGTM

2020-01-24 18:56 UTC, merged